# Generated by Django 5.2.17 on 2026-09-25 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Create the workflow definitions and execution tables."""

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TaskDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WorkflowDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LinkCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=100)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflows.link')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.taskdefinition')),
            ],
        ),
        migrations.AddField(
            model_name='link',
            name='target_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workflows.taskdefinition'),
        ),
        migrations.AddField(
            model_name='taskdefinition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowdefinition'),
        ),
        migrations.AddField(
            model_name='link',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowdefinition'),
        ),
        migrations.CreateModel(
            name='WorkflowExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=100)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowdefinition')),
            ],
        ),
        migrations.CreateModel(
            name='TaskExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(default='pending', max_length=100)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.taskdefinition')),
                ('workflow_execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowexecution')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('workflow_execution', 'task'), name='one_task_per_workflow_execution')],
            },
        ),
    ]
