# Generated by Django 5.2.17 on 2026-09-27 20:40

import django.db.models.deletion
from django.db import migrations, models


def populate_workflow_references(apps, schema_editor):
    Link = apps.get_model("workflows", "Link")
    LinkCondition = apps.get_model("workflows", "LinkCondition")
    database = schema_editor.connection.alias

    Link.objects.using(database).filter(target_task__isnull=True).update(
        target_workflow_id=models.F("workflow_id")
    )
    workflow_for_link = (
        Link.objects.using(database)
        .filter(pk=models.OuterRef("link_id"))
        .values("workflow_id")
    )
    LinkCondition.objects.using(database).filter(task__isnull=True).update(
        workflow_id=models.Subquery(workflow_for_link[:1])
    )


class Migration(migrations.Migration):

    dependencies = [
        ("workflows", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="target_workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="target_links",
                to="workflows.workflowdefinition",
            ),
        ),
        migrations.AddField(
            model_name="linkcondition",
            name="workflow",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="workflows.workflowdefinition",
            ),
        ),
        migrations.RunPython(populate_workflow_references, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="link",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("target_task__isnull", True),
                        ("target_workflow__isnull", False),
                    ),
                    models.Q(
                        ("target_task__isnull", False),
                        ("target_workflow__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="link_has_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="linkcondition",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("task__isnull", True), ("workflow__isnull", False)),
                    models.Q(("task__isnull", False), ("workflow__isnull", True)),
                    _connector="OR",
                ),
                name="condition_has_exactly_one_component",
            ),
        ),
    ]
